---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: nodejs-build
spec:
  workspaces:
    - name: shared
  params:
    - name: IMAGE_NAME
      type: string
      default: "exchange"
    - name: GIT_REPO
      type: string
      default: "https://git.ocp4.example.com/developer/DO288-apps"
    - name: GIT_REVISION
      type: string
      default: "main"
    - name: APP_PATH
      type: string
      default: "apps/pipelines-creation/exchange"
  tasks:        
  - name: fetch-repository
    taskRef:
      resolver: cluster
      params:
      - name: kind
        value: task
      - name: name
        value: git-clone
      - name: namespace
        value: openshift-pipelines
    params:
    - name: URL
      values: $(params.GIT_REPO)
    - name: REVISION
      value: $(params.GIT_REVISION)
    - name: SUBDIRECTORY
      value: ""
    - name: DELETE_EXISTING
      value: "true"
    - name: SSL_VERIFY
      value: "false"
    workspaces:
    - name: output
      workspace: shared
