#FROM registry.ocp4.example.com:8443/ubi10/nodejs-22-minimal:10.0
FROM quay.io/victorin_condei/ubi10/nodejs-22-minimal:10.0

ENV PORT=8080
EXPOSE ${PORT}


ADD . $HOME

RUN npm ci --omit=dev && rm -rf .npm

USER root
RUN chgrp -R 0 /var/cache/ && \
    chmod -R g=u /var/cache
USER 1001

CMD npm start
