#FROM registry.ocp4.example.com:8443/ubi10/nodejs-22-minimal:10.0
FROM quay.io/victorin_condei/ubi10/nodejs-22-minimal:10.0

ENV PORT=80
EXPOSE ${PORT}


ADD . $HOME

RUN npm ci --omit=dev && rm -rf .npm

CMD npm start
