apiVersion: apps/v1
kind: Deployment
metadata:
  name: famousapp-famouschart
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: famouschart
          resources:
            limits: 
              memory: "128mi"
              cpu: "128m"
