FROM default-route-openshift-image-registry.apps.rm1.0a51.p1.openshiftapps.com/openshift/nodejs:22-minimal-ubi8 as builder
ADD . .

# Allow the root group to have the same permissions as the root user
# in the application directory
USER root
RUN chgrp -R 0 . && \
    chmod -R g=u .
USER 1001

# Avoid using "npm ci" to prevent problems with the private NPM registry in the lab environment
RUN npm install --omit dev --no-package-lock

FROM default-route-openshift-image-registry.apps.rm1.0a51.p1.openshiftapps.com/openshift/nodejs:22-minimal-ubi8
COPY --from=builder $HOME $HOME
EXPOSE 3000
CMD npm run -d start
